version: 0.0
os: linux
files:
  - source: /app/server/views/index.ejs
    destination: /home/ec2-user/sample-node-project/app/server/views/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
